### ISSUE TITLE
Where are the Instructions (GIF or quick-video)

### ISSUE THREAD

**Issue by jantonioavalos** [jantonioavalos/CSS-Coordenates#5]
Currently, instructions are just a <p> line explaining how to use the tool, but unless you see de README file in the root of this project, you could get confused. This experience could be improved.

**Comment by jorgearuv** [comment]
I think there is no need of this if you can set a quick guide before the tool. 

### Example: 
1. Copy the image link.
2. Click here and there.
3. Click the button x to get results.

**Comment by jantonioavalos** [comment]
Ok but Maybe we could try to do an animation as quick-tour tutorial :P

**Comment by jorgearuv** [comment]
I think we could close up this. What do you think?
