### ISSUE TITLE
Refresh Canvas Zone

### ISSUE THREAD

**Issue by jantonioavalos** [jantonioavalos/CSS-Coordenates#6]
Now canvas overwrites the new link's image, that causes wrong coordinates if following images are smaller than previous one.

**Comment by jorgearuv** [comment]
When you don't enter any image link the "preview" box under the input field disappears. Is this issue related to that?

**Comment by jantonioavalos** [comment]
Not really, that feature is used to tell the user that image is loading (yes... it is not the best way, but here is reported as an enhancement #1 )

In other words, this issue happens like in this example:
1. You use the page for an 1200x800 image... then you git the correct coordinates
2. You paste a new link and then an 600x400 image is loaded and you use the page, but you are going to get bad coordinates, because "coodinates code blocks" are only refreshed when new code is written...
3. This case happens because the 2nd image was smaller and the Natural Coordinates was the only overwritten keeping the past image's coordinates (the bigger one).

SOLUTION: Make a refresh function that refresh code and canvas area each time the button is pressed.
